spring.application.name=transaction-service

# MySQL connection settings
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=${MYSQL_DRIVER}

# JPA performence settings
spring.jpa.properties.hibernate.dialect=${DEV_JPA_DIALECT}
spring.jpa.properties.hibernate.jdbc.batch_size=${JPA_BATCH_SIZE}
spring.jpa.properties.hibernate.default_batch_fetch_size=${JPA_STATEMENT_FETCH_SIZE}
spring.jpa.properties.hibernate.order_inserts=${JPA_ORDER_INSERTS}
spring.jpa.properties.hibernate.order_updates=${JPA_ORDER_UPDATES}
spring.jpa.properties.hibernate.connection.pool_size=${JPA_CONNECTION_POOL_SIZE}

# prod env JPA settings
spring.jpa.hibernate.ddl-auto=${DEV_JPA_DDL_AUTO}
spring.jpa.show-sql=${DEV_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${DEV_JPA_FORMAT_SQL}

spring.kafka.bootstrap-servers=localhost:9092

# Consumer
spring.kafka.consumer.group-id=transaction-service
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer